name: MLOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-suite:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model before test
        run: python src/train.py

      - name: Run Pytest
        run: PYTHONPATH=. pytest tests/

  train-and-quantize:
    name: Train and Quantize Model
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Quantize model
        run: python src/quantize.py

  build-and-test-container:
    name: Build Docker & Run Predict
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t mlops-lr-app .

      - name: Run Predict Script
        run: docker run --rm mlops-lr-app

